name: ML Pipeline

on: [push]

jobs:
  train-and-register:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install pandas scikit-learn mlflow dvc dvc-s3

      - name: Pull Data from DVC
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc remote modify origin --local access_key_id $DAGSHUB_TOKEN
          dvc remote modify origin --local secret_access_key $DAGSHUB_TOKEN
          dvc pull

      - name: Run Training and Registry
        run: python train.py